# Generated by Django 5.2.4 on 2025-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
