# Generated by Django 5.2.4 on 2025-07-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_tasks_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tasks",
            new_name="Task",
        ),
    ]
