# Generated by Django 5.2.4 on 2025-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_adminprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
