# Generated by Django 5.2.4 on 2025-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(null=True, upload_to="Media/files"),
        ),
    ]
