# Generated by Django 5.2.4 on 2025-07-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="file",
        ),
        migrations.AddField(
            model_name="task",
            name="upload",
            field=models.FileField(null=True, upload_to="documents/files"),
        ),
    ]
