# Generated by Django 5.2.5 on 2025-09-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_workupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workupdate',
            name='employee_seen',
            field=models.BooleanField(default=False, help_text='Whether the employee has seen the admin review'),
        ),
    ]
