# Generated by Django 5.2.5 on 2025-09-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_workupdate_employee_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_seen',
            field=models.BooleanField(default=False, help_text='Whether the assigned employee has seen this task'),
        ),
    ]
