# Generated by Django 5.2.4 on 2025-09-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_team_seen_alter_task_assigned_to_team_and_more'),
    ]

    operations = [
    ]
