# Generated by Django 5.2.4 on 2025-09-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_revert_team_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
