# Generated by Django 5.2.4 on 2025-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_contactmessage_first_name_contactmessage_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='testForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
    ]
